# Generated by Django 3.2 on 2023-02-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('header', models.CharField(max_length=100)),
                ('footer', models.CharField(max_length=100)),
                ('ingestion_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisterReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan_core', models.IntegerField()),
                ('meter_id', models.CharField(max_length=10)),
                ('meter_register_id', models.CharField(max_length=2)),
                ('reading_date_time', models.DateTimeField()),
                ('register_reading', models.DecimalField(decimal_places=1, max_digits=10)),
                ('md_reset_date_time', models.DateTimeField()),
                ('number_of_md_resets', models.IntegerField()),
                ('meter_reading_flag', models.BooleanField()),
                ('reading_method', models.CharField(max_length=1)),
                ('file_name', models.CharField(max_length=100)),
                ('ingestion_time', models.DateTimeField()),
            ],
        ),
    ]
