# Generated by Django 3.2 on 2023-03-15 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meter_readings', '0002_auto_20230221_0522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name_plural': 'files'},
        ),
        migrations.AlterModelOptions(
            name='registerreadings',
            options={'verbose_name_plural': 'register_readings'},
        ),
        migrations.RemoveField(
            model_name='files',
            name='id',
        ),
        migrations.AlterField(
            model_name='files',
            name='file_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registerreadings',
            name='file_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter_readings.files'),
        ),
    ]
