# Generated by Django 3.2 on 2023-03-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_readings', '0003_auto_20230315_1923'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registerreadings',
            index=models.Index(fields=['mpan_core', 'reading_date_time'], name='meter_readi_mpan_co_0af96b_idx'),
        ),
    ]
